/**
 * scripts/build.js
 *
 * Runs before `wrangler dev` or `wrangler deploy`.
 * Scans data/ and views/ and writes src/registry.js — a single
 * auto-generated module that bundles all JSON pages and pre-compiled
 * Eta template functions so the Worker can render without eval().
 */

const fs = require('fs');
const path = require('path');
const { Eta } = require('eta');

const ROOT = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const VIEWS_DIR = path.join(ROOT, 'views');
const OUT_FILE = path.join(ROOT, 'src', 'registry.js');

const eta = new Eta();

// --- Collect JSON pages ---
const pages = {};
for (const file of fs.readdirSync(DATA_DIR)) {
  if (!file.endsWith('.json')) continue;
  const name = file.replace('.json', '');
  pages[name] = JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), 'utf-8'));
}

// --- Compile Eta templates to plain functions (no eval at runtime) ---
const templateFunctions = {};
for (const file of fs.readdirSync(VIEWS_DIR)) {
  if (!file.endsWith('.eta')) continue;
  const name = file.replace('.eta', '');
  const src = fs.readFileSync(path.join(VIEWS_DIR, file), 'utf-8');
  // eta.compile() returns a function — extract its body so we can
  // reconstruct it in registry.js without needing eval() at runtime.
  const compiled = eta.compile(src);
  templateFunctions[name] = compiled.toString();
}

// --- Write registry.js ---
// Templates are stored as function source strings and reconstructed
// with new Function() once at module load time (not on every request).
const templateEntries = Object.entries(templateFunctions)
  .map(([name, fnStr]) => `  ${JSON.stringify(name)}: new Function("it", "options", ${JSON.stringify(fnStr.replace(/^function anonymous\(it,options\s*\)\s*\{/, '').replace(/\}$/, '').trim())})`)
  .join(',\n');

const output = `// AUTO-GENERATED by scripts/build.js — do not edit by hand
// Re-run \`npm run build\` after adding/changing data/ or views/ files.
// Templates are pre-compiled — no eval() used at runtime.

export const pages = ${JSON.stringify(pages, null, 2)};

export const templates = {
${templateEntries}
};
`;

fs.writeFileSync(OUT_FILE, output, 'utf-8');

const pageList = Object.keys(pages).join(', ');
const templateList = Object.keys(templateFunctions).join(', ');
console.log(`✓ registry.js written (templates pre-compiled, no eval)`);
console.log(`  pages     : ${pageList}`);
console.log(`  templates : ${templateList}`);
